import { LyricLine } from "@/components/SynchronizedLyrics";

export interface Song {
  id: string;
  title: string;
  artist: string;
  src: string;
  coverArt: string;
  description?: string;
  lyrics?: LyricLine[];
}

// Supabase Storage URLs for audio files
const SUPABASE_URL = "https://oojckbecymzrrdtvcmqi.supabase.co";
const getAudioUrl = (filename: string) => `${SUPABASE_URL}/storage/v1/object/public/audio-files/${encodeURIComponent(filename)}`;

export const SONGS: Song[] = [
  {
    id: "bc-ai-hackathon",
    title: "BC AI Hackathon by Rival Tech",
    artist: "Official Anthem",
    src: getAudioUrl("BC AI Hackathon by Rival Tech.mp3"),
    coverArt: "/lovable-uploads/b56415f7-ad61-43e6-8d05-54452f44a5be.png",
    description: `The official anthem of the BC AI Survey project, this dynamic track by Rival Technologies encapsulates the entire vision of our community-driven research initiative.`,
    lyrics: [
      { time: 0, text: "In Vancouver's buzzing scene, where coders dream big," },
      { time: 4, text: "The BC AI Hackathon calls, time to dig." },
      { time: 8, text: "Innovate, create, with passion and might," },
      { time: 12, text: "Together we build, into the night." },
      { time: 16, text: "From data to code, our spirits ignite," },
      { time: 20, text: "BC AI Hackathon, shining bright." },
    ] as LyricLine[]
  },
  {
    id: "lionel-ringenbach",
    title: "ChatGPT: Est-ce que ma facture va exploser?",
    artist: "Lionel Ringenbach",
    src: getAudioUrl("Lionel Ringenbach.mp3"),
    coverArt: "/lovable-uploads/7f8d84c3-eb81-4f66-87be-5b024084aca2.png",
    lyrics: [
      { time: 0, text: "(Verse 1)" },
      { time: 2, text: "Who says AI says innovation," },
      { time: 6, text: "But will my bill cause frustration?" },
      { time: 10, text: "ChatGPT, mon ami, dis-moi la vérité," },
      { time: 14, text: "Est-ce que ma facture va exploser?" },
      { time: 18, text: "Je pose la question, dans ce monde digital," },
      { time: 22, text: "L'IA avance, mais à quel prix final?" },
    ] as LyricLine[]
  },
  {
    id: "kris-krug-circles",
    title: "Circles in the AI Glow",
    artist: "Kris Krüg & BC + AI Crew",
    src: getAudioUrl("Kris Krug Circles in the AI Glow.mp3"),
    coverArt: "/lovable-uploads/de844c7f-f953-4326-aba2-c4344918c873.png",
    lyrics: [
      { time: 0, text: "(Intro / Pre-Verse 1)" },
      { time: 2, text: "Humanity... yeah, that's the start..." },
      { time: 6, text: "Circles spinning in the AI glow," },
      { time: 10, text: "Data streams and dreams that flow." },
      { time: 14, text: "We build the future, line by line," },
      { time: 18, text: "In this digital age, we intertwine." },
    ] as LyricLine[]
  },
  {
    id: "pixel-wizard",
    title: "Mr. Pixel Wizard BC AI",
    artist: "Kevin Friel",
    src: getAudioUrl("Mr_Pixel_Wizard BC AI.mp3"),
    coverArt: "/lovable-uploads/2c251b22-3f09-4812-bc92-ad7c64062f4b.png",
    lyrics: [
      { time: 0, text: "(Verse 1)" },
      { time: 3, text: "In a digital realm where dreams take flight," },
      { time: 7, text: "Mr. Pixel Wizard casts his light." },
      { time: 11, text: "Coding spells and magic code," },
      { time: 15, text: "Guiding AI down the road." },
    ] as LyricLine[]
  },
  {
    id: "mac-mind-ai-consciousness",
    title: "Mind, AI, & Consciousness (MAC)",
    artist: "The Algorithm Whisperer",
    src: getAudioUrl("Mind, AI, & Consciousness (MAC).mp3"),
    coverArt: "/lovable-uploads/cc181a8b-6dad-4af6-8731-9a8cbd3ba5d0.png",
    lyrics: [
      { time: 0, text: "(Intro)" },
      { time: 2, text: "Welcome to the frontier of mind..." },
      { time: 6, text: "Where AI and consciousness bind." },
      { time: 10, text: "Exploring thoughts, both real and fake," },
      { time: 14, text: "The future's path we now partake." },
    ] as LyricLine[]
  },
  {
    id: "darren-ai-struck",
    title: "AI Struck by Lightning",
    artist: "Darren McConchie",
    src: getAudioUrl("Darren AI Struck.mp3"),
    coverArt: "/lovable-uploads/cf89c28f-23f5-4188-a5aa-e50f28daa5c2.png",
    lyrics: [
      { time: 0, text: "(Verse 1)" },
      { time: 2, text: "I remember the day data changed my world..." },
      { time: 6, text: "AI struck by lightning, flags unfurled." },
      { time: 10, text: "From zeros and ones to thoughts anew," },
      { time: 14, text: "A digital spark that grew and grew." },
    ] as LyricLine[]
  },
  {
    id: "dr-patrick-cover",
    title: "Neural Networks & Coffee Dreams",
    artist: "Dr. Patrick Parra Pennefather",
    src: getAudioUrl("Dr. Patrick Parra Pennefather.mp3"),
    coverArt: "/lovable-uploads/4d050983-b56d-4606-a958-1c7e2c7253e8.png",
    lyrics: [
      { time: 0, text: "(Verse 1)" },
      { time: 2, text: "In the lab where neurons fire..." },
      { time: 6, text: "Coffee fuels the neural wire." },
      { time: 10, text: "Patterns form and thoughts align," },
      { time: 14, text: "Dreams of AI, so divine." },
    ] as LyricLine[]
  },
  {
    id: "hr-macmillan-alien",
    title: "Alien Abduction at H.R. MacMillan",
    artist: "Space Centre Stories",
    src: getAudioUrl("H.R MacMillan Space Centre _ Alian Abduction.mp3"),
    coverArt: "/lovable-uploads/8a59c6e4-39f4-41e2-bb0d-544e22e3030a.png",
    lyrics: [
      { time: 0, text: "(Intro)" },
      { time: 2, text: "The stars aligned that fateful night..." },
      { time: 6, text: "Alien abduction, a strange sight." },
      { time: 10, text: "H.R. MacMillan, tales untold," },
      { time: 14, text: "Mysteries in the cold." },
    ] as LyricLine[]
  },
  {
    id: "lalala-ai-dilemma",
    title: "La La La AI Dilemma",
    artist: "Michelle Diamond",
    src: getAudioUrl("La La La AI Dilemma_Michelle_Diamond.mp3"),
    coverArt: "/lovable-uploads/7e23b796-605f-4562-927b-06daa9147648.png",
    lyrics: [
      { time: 0, text: "(Verse 1)" },
      { time: 2, text: "La la la, the algorithms sing..." },
      { time: 6, text: "Dilemmas in the AI ring." },
      { time: 10, text: "Ethics, data, and the code," },
      { time: 14, text: "Walking down this winding road." },
    ] as LyricLine[]
  },
  {
    id: "dean-shev-human",
    title: "Still Human",
    artist: "Dean Shev",
    src: getAudioUrl("Dean Shev - Still Human.mp3"),
    coverArt: "/lovable-uploads/749e260e-38aa-4528-b1a6-a4c62cc10020.png",
    lyrics: [
      { time: 0, text: "(Verse 1)" },
      { time: 2, text: "In this digital age, I'm still human..." },
      { time: 6, text: "Heart and soul, no algorithm." },
      { time: 10, text: "Through the noise, I find my way," },
      { time: 14, text: "Still human at the end of day." },
    ] as LyricLine[]
  },
  {
    id: "bc-coast-catalyst",
    title: "BC Coast Catalyst",
    artist: "Coastal AI Collective",
    src: getAudioUrl("BC Coast Catalyst.mp3"),
    coverArt: "/lovable-uploads/429a3cb8-3ffb-40db-874a-5829a6a083bd.png",
    lyrics: [
      { time: 0, text: "(Verse 1)" },
      { time: 2, text: "From the Pacific shores to mountain peaks..." },
      { time: 6, text: "BC Coast Catalyst speaks." },
      { time: 10, text: "Innovation flows like the tide," },
      { time: 14, text: "Together we stand, side by side." },
    ] as LyricLine[]
  },
  {
    id: "deepfakes-in-the-rain",
    title: "Deepfakes in the Rain",
    artist: "Kris Krüg",
    src: getAudioUrl("Deepfakes in the Rain_KK_BCAI.mp3"),
    coverArt: "/lovable-uploads/22e18179-d389-42d3-9924-c6caf65d7d2e.png",
    lyrics: [
      { time: 0, text: "(Verse 1)" },
      { time: 2, text: "Rain falls on Vancouver's streets..." },
      { time: 6, text: "Deepfakes blur the faces we meet." },
      { time: 10, text: "Truth and fiction intertwine," },
      { time: 14, text: "In the digital rain, we redefine." },
    ] as LyricLine[]
  },
  {
    id: "philippe-pasquier-art-hallucinations",
    title: "L'Art des Hallucinations de l'IA",
    artist: "Philippe Pasquier",
    src: getAudioUrl("L'Art des Hallucinations de l'IA.mp3"),
    coverArt: "/lovable-uploads/53a7e8c9-c967-4d3d-870c-68e228c2ff3f.png",
    lyrics: [
      { time: 0, text: "(Intro – Building synth loops, male voice whispers in French over rising arpeggios)" },
      { time: 4, text: "Je suis Philippe, dans le labo de rêves..." },
      { time: 8, text: "Hallucinations of AI, reality fades away..." },
      { time: 12, text: "" },
      { time: 14, text: "(Verse 1 – Funky bass drop, male lead raps/sings in blended French-English)" },
      { time: 16, text: "From Laval to SFU, my journey begins" },
      { time: 20, text: "PhD en IA, systems that dance" },
      { time: 24, text: "Metacreation Lab, I direct the fire" },
      { time: 28, text: "Générative art, blending real with the new" },
      { time: 32, text: "Who knew? Ancestral patterns in code" },
      { time: 36, text: "French roots in Quebec, now Vancouver's road" },
      { time: 40, text: "From music to visuals, AI takes the stage" },
      { time: 44, text: "Hallucinations bloom, turning the page" },
      { time: 48, text: "" },
      { time: 50, text: "(Chorus – Big drop: Crazy synth loops swirling up and down)" },
      { time: 52, text: "L'art des hallucinations de l'IA" },
      { time: 56, text: "Blending reality, other worlds in play" },
      { time: 60, text: "Systems I build, creative and wild" },
      { time: 64, text: "Human-machine, like a dream undefiled" },
      { time: 68, text: "Hallucinations! (Female: Hallucinations!)" },
      { time: 72, text: "Dans le chaos, je crée le feu" },
      { time: 76, text: "AI art rising, breaking through!" },
      { time: 80, text: "L'art des hallucinations... oh yeah!" },
      { time: 84, text: "" },
      { time: 86, text: "(Verse 2 – Groove intensifies, male voice deeper with French emphasis)" },
      { time: 88, text: "Interactive installs, MIDI-GPT sings" },
      { time: 92, text: "Générative sounds, what the machine brings" },
      { time: 96, text: "De la musique à la danse, AI en performance" },
      { time: 100, text: "Blurring lines, human essence in trance" },
      { time: 104, text: "I refuse to strip our humanity away" },
      { time: 108, text: "Systems for chaos, meaningful and free" },
      { time: 112, text: "From GNI to labs, provoking the spark" },
      { time: 116, text: "Digital alchemist, lighting the dark" },
      { time: 120, text: "" },
      { time: 122, text: "(Chorus – Repeat with added glitch effects)" },
      { time: 124, text: "L'art des hallucinations de l'IA" },
      { time: 128, text: "Blending reality, other worlds in play" },
      { time: 132, text: "Systems I build, creative and wild" },
      { time: 136, text: "Human-machine, like a dream undefiled" },
      { time: 140, text: "Hallucinations! (Female: Hallucinations!)" },
      { time: 144, text: "Dans le chaos, je crée le feu" },
      { time: 148, text: "AI art rising, breaking through!" },
      { time: 152, text: "L'art des hallucinations... c'est moi!" },
      { time: 156, text: "" },
      { time: 158, text: "(Bridge – Slow build: Synth loops go wild, up-down frenzy)" },
      { time: 160, text: "Part digital hacker, part cultural flame" },
      { time: 164, text: "From Quebec's wisdom to AI's game" },
      { time: 168, text: "Je tisse Indigenous keys into code's embrace" },
      { time: 172, text: "Ancestral protocols, in this digital space" },
      { time: 176, text: "Hallucinations rise, reality bends" },
      { time: 180, text: "But humanity stays, where the journey ends" },
      { time: 184, text: "(Female: Rêves... hallucinations... réalité...)" },
      { time: 188, text: "" },
      { time: 190, text: "(Outro – Final drop: Loops peak in chaotic up-down waves)" },
      { time: 192, text: "L'art des hallucinations, my life's grand quest" },
      { time: 196, text: "Philippe Pasquier, blending east and west" },
      { time: 200, text: "AI hallucinations, forever we play..." },
      { time: 204, text: "(Female: Hallucinations... l'art de l'IA...)" },
      { time: 208, text: "Fade into dreams, where realities meet..." },
      { time: 212, text: "Oh, l'art des hallucinations!" }
    ] as LyricLine[]
  },
  {
    id: "indigenomics-ai",
    title: "Indigenomics AI, that's where we start",
    artist: "Carol Anne Hilton",
    src: getAudioUrl("Indigenomics AI, that's where we start.mp3"),
    coverArt: "/lovable-uploads/8d6e4150-076b-4f1c-840b-595c15a55048.png",
    lyrics: [
      { time: 0, text: "I'm Carol Anne Hilton, with a sparkle and a plan," },
      { time: 4, text: "Hesquiaht roots run deep, from Ahousaht and Makah land." },
      { time: 8, text: "Indigenomics rising, AI hummin' like a band," },
      { time: 12, text: "Blending ancient wisdom with tech in my hand." },
      { time: 16, text: "" },
      { time: 18, text: "Numbers with a heartbeat, policy with a grin," },
      { time: 22, text: "Economic empowerment, let the journey begin—" },
      { time: 26, text: "Who wants to play Indigenomics? Come on in!" },
      { time: 30, text: "" },
      { time: 32, text: "Oh, Indigenomics, take a seat at the table so grand," },
      { time: 36, text: "Relationships weaving, stewardship across the land." },
      { time: 40, text: "Sovereign data dancing, stories in the code," },
      { time: 44, text: "Future's bright and bold on this Indigenous road." },
      { time: 48, text: "" },
      { time: 50, text: "Care for all, commerce with heart," },
      { time: 54, text: "Indigenomics AI, that's where we start—" },
      { time: 58, text: "Everybody sing, let the movement ignite!" },
      { time: 62, text: "" }
    ] as LyricLine[]
  },
  {
    id: "my-arts-all-human",
    title: "My art's all human, soul-deep and true",
    artist: "Michelle Diamond",
    src: getAudioUrl("My art's all human, soul-deep and true.mp3"),
    coverArt: "/lovable-uploads/ce458784-2685-46f2-a7ea-3c2e6e1143ea.png",
    description: `A humorous photographer's anthem about maintaining creative authenticity in the AI age. Through the eyes of Photographer Michelle, this witty track captures the pride and irony of human artistry while secretly embracing AI assistance. Set in Vancouver's vibrant AI community, it features Dr. Patrick Parra Pennefather's famous catchphrase "There is an AI for that" while celebrating the irreplaceable human spirit behind the lens.`,
    lyrics: [
      { time: 0, text: "(Verse 1)" },
      { time: 2, text: "In Vancouver's AI whirl, where ideas spark and spin," },
      { time: 6, text: "I'm Photographer Michelle, capturing it all from within." },
      { time: 10, text: "At every event, my camera's my trusty sword," },
      { time: 14, text: "Snapping Kris Krug leading, and the crowd's roaring chord." },
      { time: 18, text: "From hackathons humming to MAC's thoughtful night," },
      { time: 22, text: "I freeze the magic moments in the soft event light." },
      { time: 26, text: "Proud of my craft, with heart in every frame," },
      { time: 30, text: "No bot can steal my thunder, or play my game." },
      { time: 34, text: "" },
      { time: 36, text: "(Chorus)" },
      { time: 38, text: "Oh, I'm irreplaceable, the queen behind the lens," },
      { time: 42, text: "In this AI playground, where the future begins." },
      { time: 46, text: "Dr. Patrick Parra Pennefather might wink and say," },
      { time: 50, text: "\"There is an AI for that,\" but not today." },
      { time: 54, text: "My art's all human, soul-deep and true," },
      { time: 58, text: "Proudly I stand, seeing the world anew." },
      { time: 62, text: "Keep on clicking, let my vision take flight!" }
    ] as LyricLine[]
  },
  {
    id: "eagle-watch-inlet",
    title: "Eagle's Watch Over the Inlet",
    artist: "Gabriel George Sr.",
    src: getAudioUrl("Eagle's Watch Over the Inlet.mp3"),
    coverArt: "/lovable-uploads/6b65586a-63ba-48f1-9c56-1846ec800f39.png",
    lyrics: [
      { time: 0, text: "Hey-ya, hey-ya, the wings beat strong," },
      { time: 5, text: "I stand before you today with an open heart and mind," },
      { time: 10, text: "To all of you, my dear friends and family," },
      { time: 15, text: "I welcome you to this village of suh-nak," },
      { time: 20, text: "The inlet where waters whisper ancient truths." },
      { time: 25, text: "I give gratitude to the ancestors—" },
      { time: 30, text: "mus-kwee-um, skwaw-mish, and my ts-lay-wah-tooth kin." },
      { time: 35, text: "Our families have walked these lands since time out of mind," },
      { time: 40, text: "Rooted like the cedars, flowing like the tides." },
      { time: 50, text: "[Verse 1: Stories of the Changing Land]" },
      { time: 55, text: "My late uncle shared tales of the elk herds," },
      { time: 60, text: "Gathering high on Burnaby Mountain—sul-ts-munt suh-suh-nuk, we call it." },
      { time: 65, text: "They'd descend to suh-nak-w, into False Creek's embrace," },
      { time: 70, text: "Where our hunters waited, bows drawn in respect." },
      { time: 75, text: "But oh, how the land has shifted under our feet—" },
      { time: 80, text: "False Creek once stretched to Clark Avenue, up to Terminal's edge," },
      { time: 85, text: "Entering the inlet from the south at high tide, not this narrowed path." },
      { time: 90, text: "Giant cedars once pierced the sky, an ancient rainforest we sustained," },
      { time: 95, text: "For thousands of years, in harmony we remained." },
      { time: 100, text: "The land my grandfather, Chief Dan George, knew so well—" },
      { time: 105, text: "It's faded, transformed, a story we must tell." },
      { time: 115, text: "[Chorus – Eagle Song Invocation]" },
      { time: 120, text: "Kway-tal-us puk-wus, the eagle is watching over us," },
      { time: 125, text: "Flying high since time out of mind, carrying our prayers." },
      { time: 130, text: "To the ancestors, to the great spirit above," },
      { time: 135, text: "Set good intentions for your circle, for love." },
      { time: 140, text: "Hey-ya, hey-ya, the wings beat strong," },
      { time: 145, text: "Over suh-ley-l-wut, where we belong." },
      { time: 150, text: "Kway-tal-us puk-wus, watch over us all." }
    ] as LyricLine[]
  },
  {
    id: "smells-like-reids-spirit",
    title: "Smells Like Reid's Spirit",
    artist: "Andrew Reid",
    src: getAudioUrl("Smells Like Reid's Spirit.mp3"),
    coverArt: "/lovable-uploads/92abee24-4e67-43a3-a956-1a845e0b1b1f.png",
    lyrics: [
      { time: 0, text: "(Verse 1)" },
      { time: 2, text: "Here we are now, entertainers" },
      { time: 6, text: "Building platforms, code arrangers" },
      { time: 10, text: "Tech innovator, startup dangers" },
      { time: 14, text: "Venture capital, angel strangers" },
      { time: 18, text: "" },
      { time: 20, text: "With the AI lights out, it's less dangerous" },
      { time: 24, text: "Here we are now, Vancouver famous" },
      { time: 28, text: "I'm Andrew Reid, tech contagious" },
      { time: 32, text: "BC startup scene, how outrageous!" },
      { time: 36, text: "" },
      { time: 38, text: "(Chorus)" },
      { time: 40, text: "Smells like Reid's spirit (Yeah!)" },
      { time: 44, text: "Smells like Reid's spirit (Hey!)" },
      { time: 48, text: "Smells like Reid's spirit (Whoa!)" },
      { time: 52, text: "Smells like Reid's spirit!" },
      { time: 56, text: "" },
      { time: 58, text: "(Verse 2)" },
      { time: 60, text: "From the dot-com boom to the AI rise" },
      { time: 64, text: "Building systems, scaling enterprise" },
      { time: 68, text: "Coffee shops to boardroom ties" },
      { time: 72, text: "Vancouver hustle, no compromise" },
      { time: 76, text: "" },
      { time: 78, text: "When the funding's out, it's less dangerous" },
      { time: 82, text: "Here we are now, pitch deck famous" },
      { time: 86, text: "A Canadian tech scene, so contagious" },
      { time: 90, text: "West Coast innovation, how outrageous!" }
    ] as LyricLine[]
  }
];
