-- Add keywords for "Eagle's Watch Over the Inlet" by Gabriel George Sr.
INSERT INTO song_keywords (song_id, keyword, category, relevance_score) VALUES
('gabriel-george-sr-eagles-watch', 'Indigenous language', 'Indigenous Culture', 0.95),
('gabriel-george-sr-eagles-watch', 'mus-kwee-um', 'Indigenous Culture', 0.90),
('gabriel-george-sr-eagles-watch', 'skwaw-mish', 'Indigenous Culture', 0.90),
('gabriel-george-sr-eagles-watch', 'ts-lay-wah-tooth', 'Indigenous Culture', 0.90),
('gabriel-george-sr-eagles-watch', 'hal-ko-may-lum', 'Indigenous Culture', 0.90),
('gabriel-george-sr-eagles-watch', 'regalia', 'Indigenous Culture', 0.85),
('gabriel-george-sr-eagles-watch', 'ceremony', 'Indigenous Culture', 0.90),
('gabriel-george-sr-eagles-watch', 'drum', 'Indigenous Culture', 0.80),
('gabriel-george-sr-eagles-watch', 'prayer', 'Indigenous Culture', 0.85),
('gabriel-george-sr-eagles-watch', 'cedar', 'Indigenous Culture', 0.85),
('gabriel-george-sr-eagles-watch', 'feathers', 'Indigenous Culture', 0.80),
('gabriel-george-sr-eagles-watch', 'suh-nak', 'Indigenous Culture', 0.85),
('gabriel-george-sr-eagles-watch', 'inlet', 'Indigenous Culture', 0.90),
('gabriel-george-sr-eagles-watch', 'village', 'Indigenous Culture', 0.75),
('gabriel-george-sr-eagles-watch', 'kohst say-lish', 'Indigenous Culture', 0.80),
('gabriel-george-sr-eagles-watch', 'eagle', 'Environmental Heritage', 0.95),
('gabriel-george-sr-eagles-watch', 'kway-tal-us', 'Environmental Heritage', 0.95),
('gabriel-george-sr-eagles-watch', 'elk herds', 'Environmental Heritage', 0.80),
('gabriel-george-sr-eagles-watch', 'ancient cedars', 'Environmental Heritage', 0.85),
('gabriel-george-sr-eagles-watch', 'rainforest', 'Environmental Heritage', 0.80),
('gabriel-george-sr-eagles-watch', 'False Creek', 'Environmental Heritage', 0.85),
('gabriel-george-sr-eagles-watch', 'Burnaby Mountain', 'Environmental Heritage', 0.80),
('gabriel-george-sr-eagles-watch', 'sul-ts-munt suh-suh-nuk', 'Environmental Heritage', 0.80),
('gabriel-george-sr-eagles-watch', 'interconnectedness', 'Environmental Heritage', 0.90),
('gabriel-george-sr-eagles-watch', 'earth care', 'Environmental Heritage', 0.85),
('gabriel-george-sr-eagles-watch', 'web of life', 'Environmental Heritage', 0.85),
('gabriel-george-sr-eagles-watch', 'waters', 'Environmental Heritage', 0.75),
('gabriel-george-sr-eagles-watch', 'Chief Dan George', 'Community', 0.90),
('gabriel-george-sr-eagles-watch', 'Leonard George', 'Community', 0.85),
('gabriel-george-sr-eagles-watch', 'ancestors', 'Community', 0.90),
('gabriel-george-sr-eagles-watch', 'family legacy', 'Community', 0.85),
('gabriel-george-sr-eagles-watch', 'circle', 'Community', 0.80),
('gabriel-george-sr-eagles-watch', 'unity', 'Community', 0.85),
('gabriel-george-sr-eagles-watch', 'bridge gaps', 'Community', 0.80),
('gabriel-george-sr-eagles-watch', 'common ground', 'Community', 0.80),
('gabriel-george-sr-eagles-watch', 'residential schools', 'Identity', 0.85),
('gabriel-george-sr-eagles-watch', 'cultural healing', 'Identity', 0.90),
('gabriel-george-sr-eagles-watch', 'language preservation', 'Identity', 0.85),
('gabriel-george-sr-eagles-watch', 'storytelling', 'Identity', 0.80),
('gabriel-george-sr-eagles-watch', 'heritage', 'Identity', 0.85),
('gabriel-george-sr-eagles-watch', 'root words', 'Identity', 0.75),
('gabriel-george-sr-eagles-watch', 'great spirit', 'Relationships', 0.90),
('gabriel-george-sr-eagles-watch', 'intentions', 'Relationships', 0.80),
('gabriel-george-sr-eagles-watch', 'love', 'Relationships', 0.85),
('gabriel-george-sr-eagles-watch', 'sacred bonds', 'Relationships', 0.85),
('gabriel-george-sr-eagles-watch', 'extended family', 'Relationships', 0.80),
('gabriel-george-sr-eagles-watch', 'AI fire', 'Future Vision', 0.85),
('gabriel-george-sr-eagles-watch', 'technology tools', 'Future Vision', 0.80),
('gabriel-george-sr-eagles-watch', 'modern world', 'Future Vision', 0.75),
('gabriel-george-sr-eagles-watch', 'connections', 'Future Vision', 0.80),
('gabriel-george-sr-eagles-watch', 'healing', 'Future Vision', 0.85);