// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oojckbecymzrrdtvcmqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vamNrYmVjeW16cnJkdHZjbXFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTI1OTUsImV4cCI6MjA2OTk4ODU5NX0.99nEhB_icQaEd3gy0npzADA7fnjEq4wccwDQxucV9OU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});